"""empty message

Revision ID: 2c87264ce83b
Revises: 
Create Date: 2019-12-12 19:30:14.506833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c87264ce83b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=65), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open_key_client', sa.LargeBinary(), nullable=True),
    sa.Column('private_key_server', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_place', sa.String(length=80), nullable=True),
    sa.Column('login', sa.String(length=120), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    op.drop_table('user')
    # ### end Alembic commands ###
